### ISSUE TITLE
Quorum Support Epic

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#1657]
We seem to have left Quorum out of our design and test for Truffle v5. Let's use this issue as an Epic to account for the work necessary to make Truffle work with Quorum again. 

To be clear, the goal of this issue is full support in Truffle for Quorum. This may include adopting/utilizing/integrating features of Quorum which weren't adequately integrated in prior Truffle versions. As always our goal is to make support as out of the box as possible, but for the sake of pragmatism minimal user-initiated configuration steps, installation of extra dependencies, or other similar tasks are fine, provided they are straightforward. That said, any user-initiated steps required for full Quorum support should be addressed in our user docs on our website before this issue should be considered resolved.

Issues in this epic (for non-zenhub users):

- [x] [Accommodate broken support for Quorum/other chains via `--legacy` flags to use old code](https://github.com/trufflesuite/truffle/issues/1543) - **Available in [v5.0.9](https://github.com/trufflesuite/truffle/releases/tag/v5.0.9)**
- [x] [`truffle migrate` on private permissioned Quorum network returns nothing to console](https://github.com/trufflesuite/truffle/issues/1622) - **Available in [v5.0.9](https://github.com/trufflesuite/truffle/releases/tag/v5.0.9)**
- [x] [Add support for Quorum's privateFor transaction parameter](https://github.com/trufflesuite/truffle/issues/1656) - **Available in [v5.0.14](https://github.com/trufflesuite/truffle/releases/tag/v5.0.14)**
- [ ] [Add support for signing Quorum private transactions](https://github.com/trufflesuite/truffle/issues/2153)
- [ ] [Audit Truffle's existing features/APIs for compatibility with/exposure of Quorum's feature set](https://github.com/trufflesuite/truffle/issues/1658)

**Comment by dgrmunch** [comment]
How is this going? Is there any deadline? Thanks!

**Comment by seesemichaelj** [comment]
Thanks @dgrmunch for reaching out!

We're still working on this. This issue is an Epic for a handful of smaller issues. We're still working on the first in the list: #1543. We'll update this issue as we complete sub-issues!

Unfortunately, we don't currently have a deadline or expected finish date at this point.

**Comment by seesemichaelj** [comment]
[v5.0.9](https://github.com/trufflesuite/truffle/releases/tag/v5.0.9) has been released which provides basic Quorum support again!

Please let us know if you have any issues or questions! You can [read documentation on the necessary changes to use Quorum here](https://truffleframework.com/docs/truffle/getting-started/working-with-quorum).

**Comment by DavidBurela** [comment]
Nice to see progress being made on this!
Looking forward to private transactions being supported again.

FYI Quorum just merged a PR that adds `sendRawTransaction`, which may help
https://github.com/jpmorganchase/quorum/pull/591

**Comment by seesemichaelj** [comment]
Thanks for the heads up! Will take a look at it!

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance as this is not an active endeavor.
