### ISSUE TITLE
Enable in-test breaking to use Truffle's debugger

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2206]
**Epic**. Contains issues:
- [x] ~#2204 Support debugging estimateGas operations~ calling out of scope for now
- [x] #2212 Provide new truffle-compile interface
- [x] #2205 Support debugging contract creation operations

Related PRs:
- [x] #2252 Build mocha hook for truffle-debugger
- [x] #2253 Provide in-test debugging interrupts for Solidity inside JS tests
- [x] #2255 Switch debugger to use new compile interface
- [x] #2260 Emit deploy method information in truffle-contract-lifecycle
