### ISSUE TITLE
Provide new truffle-compile interface

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2212]
**Epic**. Contains issues:

- [x] #2207 Expose new truffle-compile interface via truffle-workflow-compile
- [x] #2208 Shim legacy compile interface as new interface
- [x] ~#2209 Provide new compile interface for Vyper compiler integration~ out of scope for now, covered by #2208 
- [x] ~#2210 Provide new compile interface for the external compiler integration~ same
- [x] #2211 Update in-test debugging infrastructure to use new compile interface

Related PRs:
- [x] #2109 Refactor truffle-compile's solc integration
- [x] #2073 Introduce new truffle-compile interface
- [x] #2254 Switch `truffle test` to use new compile interface
- [x] #2258 Add missing defaults for shimBytecode

_This is part of epic #2206_

**Comment by gnidan** [comment]
This is done!
